config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'sending_destinations', to: 'users/registrations#new_sending_destination'
    post 'sending_destinations', to: 'users/registrations#create_sending_destination'
  end
  root "items#index"

  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: :show do
      collection do
        post 'pay'
      end
    end
    collection do
      get 'search'
    end
  end
  resources :users do
    collection do
      get 'credit_register'
      get 'logout'
    end
  end
  resources :credit_cards, only: [:new, :create, :show, :destroy] 
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  require 'payjp'
  Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

  def self.create_card_to_payjp(params)
    # トークンを作成 
    token = Payjp::Token.create({
      card: {
        number:     params['number'],
        cvc:        params['cvc'],
        exp_month:  params['valid_month'],
        exp_year:   params['valid_year']
      }},
      {'X-Payjp-Direct-Token-Generate': 'true'} 
    )
    # 上記で作成したトークンをもとに顧客情報を作成
    Payjp::Customer.create(card: token.id)
  end
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_card, only: [:show, :destroy]
  before_action :set_payjpSecretKey, except: :new

  require "payjp"

  def new
    @creditCard = CreditCard.new
    gon.payjpPublicKey = Rails.application.credentials[:payjp][:PAYJP_PUBLIC_KEY]
  end

  def create
    render action: :new if params['payjpToken'].blank?
    customer = Payjp::Customer.create(
      card: params['payjpToken'],
    )
    @creditcard = CreditCard.new(
      user_id: current_user.id, 
      customer_id: customer.id, 
      card_id: customer.default_card
      )
    if @creditcard.save
      flash[:notice] = 'クレジットカードの登録が完了しました'
      redirect_to controller: "users", action: 'credit_register'
    else
      flash[:alert] = 'クレジットカード登録に失敗しました'
      redirect_to action: :new
    end
  end

   def show
    redirect_to action: :new if @card.blank?
    customer = Payjp::Customer.retrieve(@card.customer_id)
    default_card_information = customer.cards.retrieve(@card.card_id)
    @exp_month = default_card_information.expiration_month.to_s
    @exp_year = default_card_information.expiration_year.to_s.slice(2,3)
    customer_card = customer.cards.retrieve(@card.card_id)
    @card_brand = customer_card.brand
    case @card_brand
    when "Visa"
      @card_src = "icon_visa.png"
    when "JCB"
      @card_src = "icon_jcb.png"
    when "MasterCard"
      @card_src = "icon_mastercard.png"
    when "American Express"
      @card_src = "icon_amex.png"
    when "Diners Club"
      @card_src = "icon_diners.png"
    when "Discover"
      @card_src = "icon_discover.png"
    end
  end

  def destroy
    customer = Payjp::Customer.retrieve(@card.customer_id)
    @card.delete
    customer.delete
    redirect_to controller: :users, action: :index
  end

  private
  def set_card
    @card = CreditCard.where(user_id: current_user.id).first
  end

  def set_payjpSecretKey
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
  end

end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_show.html.haml
.payment
  .payment__content
    .payment__content__cardImage
      = image_tag "cards/#{@card_src}", width: 40, height: 28
    .payment__content__details
      .payment__content__details__cardNumber
        = "**** **** **** " + @card_info.last4
      .payment__content__details__cardMMYY
        = @exp_month + " / " + @exp_year
  .payment__cardDelete
    = button_to "削除する", credit_card_path(@card.id), {method: :delete, id: 'charge-form', name: "inputForm", class: "payment__cardDelete__deleteBtn"}

app/views/credit_cards/new.html.haml
.wrapper
  .signup-header
    = link_to root_path do
      = image_tag "logo.png", width: 140, height: 40
  .cardAdd 
    .title 
      クレジットカード情報入力
    .cardForm
      = form_with model: @creditCard, id: "form" do |f|
        .cardForm__number
          = f.label :カード番号, class: "cardForm__number__title"
          %span.must_check 必須
        .cardForm__field
          = f.text_field :card_number, id: "card_number", placeholder: "半角数字のみ", class: "form-group__input", maxlength: 16
        .cardForm__image
          = image_tag(image_path('cards/icon_visa.png'), class: 'visa', width: 58, height: 28)
          = image_tag(image_path('cards/icon_mastercard.png'), class: 'master', width: 47, height: 36)
          = image_tag(image_path('cards/icon_jcb.png'), class: 'jcb', width: 40, height: 30)
          = image_tag(image_path('cards/icon_amex.png'), class: 'amex', width: 40, height: 30)
          = image_tag(image_path('cards/icon_diners.png'), class: 'diners', width: 45, height: 32)
          = image_tag(image_path('cards/icon_discover.png'), class: 'discover', width: 47, height: 30)
        .cardForm__expirationdate
          .cardForm__expirationdate__details
            = f.label :有効期限
            %span.must_check 必須
            %br
          .cardForm__expirationdate__choice
            .cardForm__expirationdate__choice__month
              = f.select :expiration_month, options_for_select(["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]), {}, {id: "exp_month", name: "exp_month", type: "text"}
              = f.label :月, class: "cardForm__expirationdate__choice__month__label"
            .cardForm__expirationdate__choice__year
              = f.select :expiration_year, options_for_select((2020..2030)), {}, {id: "exp_year", name: "exp_year", type: "text"}
              = f.label :年, class: "cardForm__expirationdate__choice__year__label"
        .cardForm__securitycode
          .cardForm__securitycode__details
            .cardForm__securitycode__details__title 
              = f.label :セキュリティコード, class: "label"
              %span.must_check 必須
            .cardForm__securitycode__details__field
              = f.text_field :cvc,  id: "cvc", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4"
            .cardForm__securitycode__details__hatena
              = link_to "カード背面の番号とは?", "#", class: "cardForm__securitycode__details__hatena__link"
        #card_token
          = f.submit "登録する", id: "token_submit", url: credit_cards_path, method: :post
  .signup-footer
    %nav.signup-footer__nav
      %ul.signup-footer__nav__lists
        %li.signup-footer__nav__lists__list
          = link_to '#' do
            プライバシーポリシー
        %li.signup-footer__nav__lists__list
          = link_to '#' do
            メルカリ利用規約
        %li.signup-footer__nav__lists__list
          = link_to '#' do
            特定商取引に関する表記
    = link_to root_path, class: 'signup-footer__logo' do
      = image_tag "logo/logo-white.png", height: '30', width: '120', class: "signup-footer__logo__tag"
    .signup-footer__bottom
      © FURIMA