config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'sending_destinations', to: 'users/registrations#new_sending_destination'
    post 'sending_destinations', to: 'users/registrations#create_sending_destination'
  end
  root "items#index"

  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: :show do
      collection do
        post 'pay'
      end
    end
    collection do
      get 'search'
    end
  end
  resources :users do
    collection do
      get 'credit_register'
      get 'logout'
    end
  end
  resources :credit_cards, only: [:new, :create, :show, :destroy] 
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_item
  before_action :set_card
  before_action :set_payjpSecretKey

  require "payjp"

  def show
    redirect_to item_path(@item.id) if @item.buyer_id.present?
    @item_img = @item.item_imgs[0]
    @sending_destination = current_user.sending_destination
    prefecture = Prefecture.data.select{|o| o[:id] == @sending_destination.prefecture_id}.first
    @prefectureName = prefecture[:name]
    if @card.present?
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.retrieve(@card.card_id)
      @exp_month = @card_info.exp_month.to_s
      @exp_year = @card_info.exp_year.to_s.slice(2,3)
    end
  end

  def pay
    purchase = Payjp::Charge.create(
    amount: @item.price,
    customer: @card.customer_id,
    currency: 'jpy',
    card: params['payjpToken']
    )
    if purchase.save
      @item_buyer = Item.find(params[:item_id])
      @item_buyer.update(buyer_id: current_user.id)
      flash[:notice] = '購入が完了しました'
      redirect_to root_path
    else
      flash[:notice] = '購入に失敗しました'
      redirect_to :show
    end
  end

  private
  def set_item
    @item = Item.find(params[:item_id])
  end

  def set_card
    @card = CreditCard.where(user_id: current_user.id).first
  end

  def set_payjpSecretKey
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/new.html.haml
.wrapper
  .signup-header
    = link_to root_path do
      = image_tag "logo.png", width: 140, height: 40
  .details
    .details-content
      .details-content__head
        購入内容の確認
      .details-content__inner
        .details-content__inner__item
          .details-content__inner__item__image
            = @item.item_imgs.url, width: 80, height: 80
          .details-content__inner__item__detail
            .details-content__inner__item__detail__itemName
              = @item.name
              .details-content__inner__item__detail__itemName__form
                %span.details-contet__inner__item__detail__itemName__form__price
                  = "#{convertToJPY(@product.price)}円"
                %span.details-content__inner__item__detail__itemName__form__fee
                  - if @item.delivery_charge_id == '1'
                    送料込み
                  - else
                    着払い
      .details-content__table
        %span.details-content__pricecell
          支払い金額
        %span.details-content__pricecell
          = "#{convertToJPY(@product.price)}円"
        %ul.details-content__accordion
          %li.details-content__accordion__parent
            .details-content__accordion__parent__checkBox
              %input#box1{:type => "checkbox"}/
              %label{:for => "box1"} ポイントを使用(所持ポイント:P0)
      .details-content__info
        .details-content__inner
          配送先
          %address.details-content__user
            ="〒 #{@sending_destination.post_code}"
            %br
            %br
              = @sending_destination.prefecture_code + @sending_destination.city
            %br
              = @sending_destination.house_number + @sending_destination.building_name
          = link_to "#", class: 'details-content__fix' do
            %span 変更する
            = icon 'fas', 'chevron-right'
      #details-bottom.details-content__info
        .details-content__inner
          支払い方法
          .details-content__infotext
          - if @default_card_information.blank?
            %br 
              = link_to new_credit_card_path do
                登録してください
          - else
            -#以下カード情報を表示
            **** **** **** #{@default_card_information.last4}
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          %br
          = link_to  credit_register_users_path, class: 'details-content__fix' do
            %span 変更する
            = icon 'fas', 'chevron-right'
      .details-content__btnText
        = button_tag "購入する", class:"details-content__btn"
  .signup-footer
    %nav.signup-footer__nav
      %ul.signup-footer__nav__lists
        %li.signup-footer__nav__lists__list
          = link_to '#' do
            プライバシーポリシー
        %li.signup-footer__nav__lists__list
          = link_to '#' do
            メルカリ利用規約
        %li.signup-footer__nav__lists__list
          = link_to '#' do
            特定商取引に関する表記
    = link_to root_path, class: 'signup-footer__logo' do
      = image_tag "logo/logo-white.png", height: '30', width: '120', class: "signup-footer__logo__tag"
    .signup-footer__bottom
      © FURIMA

app/views/purchases/show.html.haml
.wrapper
  .signup-header
    = link_to root_path do
      = image_tag "logo.png", width: 140, height: 40
  .details
    .details-content
      .details-content__head
        購入内容の確認
      .details-content__inner
        .details-content__inner__item
          .details-content__inner__item__image
            = image_tag @item_img.url.url, width: 100, height: 100
          .details-content__inner__item__detail
            .details-content__inner__item__detail__itemName
              = @item.name
              .details-content__inner__item__detail__itemName__form
                %span.details-contet__inner__item__detail__itemName__form__price
                  = "#{convertToJPY(@item.price)}円 (税込み)"
                %span.details-content__inner__item__detail__itemName__form__fee
                  - if @item.postage_payer_id == '1'
                    送料込み
                  - else
                    着払い
      .details-content__table
        %span.details-content__pricecell
          支払い金額
        %span.details-content__pricecell
          = "#{convertToJPY(@item.price)}円"
        %ul.details-content__accordion
          %li.details-content__accordion__parent
            .details-content__accordion__parent__checkBox
              %input#box1{:type => "checkbox"}/
              %label{:for => "box1"} ポイントを使用(所持ポイント:P0)
      .details-content__info
        .details-content__inner
          配送先
          %address.details-content__user
            ="〒 #{@sending_destination.post_code}"
            %br
            %br
              = @prefectureName + @sending_destination.city
            %br
              = @sending_destination.house_number + @sending_destination.building_name
          = link_to sending_destinations_path, class: 'details-content__fix' do
            %span 変更する
            = icon 'fas', 'chevron-right'
      #details-bottom.details-content__info
        .details-content__inner
          支払い方法
          .details-content__infotext
          - if @card == nil
            %br
              = link_to "登録してください", new_credit_card_path, class: "details-content__infotext__register"
          - else
            .customer-card__content--number.form_space
              = "**** **** **** " + @card_info.last4
            .customer-card__content--expired.form_space
              = @exp_month + " / " + @exp_year
            %br
            = link_to credit_register_users_path, class: 'details-content__fix' do
              %span 変更する
              = icon 'fas', 'chevron-right'
      .details-content__btnText
        -if @card_info.blank? || @sending_destination.blank?
          = button_to "購入する", pay_item_purchases_path, {method: :post, class: "details-content__nobtn"}
        - else
          = button_to "購入する", pay_item_purchases_path, {method: :post, class: "details-content__btn"}
        
  .signup-footer
    %nav.signup-footer__nav
      %ul.signup-footer__nav__lists
        %li.signup-footer__nav__lists__list
          = link_to '#' do
            プライバシーポリシー
        %li.signup-footer__nav__lists__list
          = link_to '#' do
            メルカリ利用規約
        %li.signup-footer__nav__lists__list
          = link_to '#' do
            特定商取引に関する表記
    = link_to root_path, class: 'signup-footer__logo' do
      = image_tag "logo/logo-white.png", height: '30', width: '120', class: "signup-footer__logo__tag"
    .signup-footer__bottom
      © FURIMA