config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'sending_destinations', to: 'users/registrations#new_sending_destination'
    post 'sending_destinations', to: 'users/registrations#create_sending_destination'
  end
  root "items#index"

  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: :show do
      collection do
        post 'pay'
      end
    end
    collection do
      get 'search'
    end
  end
  resources :users do
    collection do
      get 'credit_register'
      get 'logout'
    end
  end
  resources :credit_cards, only: [:new, :create, :show, :destroy] 
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :item_imgs, dependent: :destroy
  accepts_nested_attributes_for :item_imgs, allow_destroy: true
  has_one :user_evaluation

  belongs_to :category
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true

  
  belongs_to_active_hash :size
  belongs_to_active_hash :item_condition
  belongs_to_active_hash :postage_payer
  belongs_to_active_hash :postage_type
  belongs_to_active_hash :preparation_day
  belongs_to_active_hash :brand
  belongs_to_active_hash :prefecture

  validates :item_imgs,           presence: true
  validates :name,                presence: true, length: { maximum: 40 }
  validates :introduction,        presence: true, length: { maximum: 1000 }
  validates :category_id,         presence: true
  validates :item_condition_id,   presence: true
  validates :postage_payer_id,    presence: true
  validates :prefecture_id,       presence: true
  validates :preparation_day_id,  presence: true
  validates :price,               presence: true, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates :seller_id,           presence: true
  validates :size_id,             presence: true
  validates :postage_type_id,     presence: true

  def first_image
    item_imgs.first
  end

  scope :search, -> (search){where('name LIKE(?)', "%#{search}%")}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only:[:show,:destroy, :edit, :update]

  def index
    @parents = Category.where(ancestry: nil)
    @items = Item.includes(:item_imgs).order("created_at DESC")
  end

  def new
    @item = Item.new
    @item.item_imgs.new
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
  end

  def create
    @item = Item.new(item_params)
    @item.seller_id = current_user.id
    if @item.save
      flash[:notice] = '出品が完了しました'
      redirect_to root_path
    else
      @item.item_imgs.new
      render :new
    end
  end

  def show
    
  end

  def destroy
    if @item.seller_id == current_user.id && @item.destroy
      redirect_to root_path
      flash[:notice] = '商品の削除が完了しました'
    else
      render "items/show"
    end
  end

  def search
    @items = Item.search(params[:keyword])
    @parents = Category.where(ancestry: nil)
  end

  def count
    @cnt = Item.where(name: '検索結果').count
    render text: "検索結果は#(cnt)個です。"
  end

  def edit
    grandchild_category = @item.category
    child_category = grandchild_category.parent
    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end
    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end

  def update
    if @item.update(item_update_params)
      flash[:notice] = '商品の編集が完了しました'
      redirect_to item_path(@item)
    else
      grandchild_category = @item.category
      child_category = grandchild_category.parent
      @category_parent_array = []
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
      end
      @category_children_array = []
      Category.where(ancestry: child_category.ancestry).each do |children|
        @category_children_array << children
      end
      @category_grandchildren_array = []
      Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
        @category_grandchildren_array << grandchildren
      end
      render :edit
  end
end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :category_id, :brand_id, :size_id, :postage_type_id, :item_condition_id, :postage_payer_id, :prefecture_id, :preparation_day_id, :price, :seller_id, :buyer_id, item_imgs_attributes: [:url])
  end
  
  def item_update_params
    params.require(:item).permit(:updated_at, :name, :introduction, :category_id, :brand_id, :size_id, :postage_type_id, :item_condition_id, :postage_payer_id, :prefecture_id, :preparation_day_id, :price, :seller_id, :buyer_id, [item_imgs_attributes: [:url, :_destroy, :id]])
  end
  

  def set_item
    @item = Item.find(params[:id])
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
  def convertToJPY(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/items/_item.html.haml
- if item.buyer_id.nil?
  .pickup-container__product-box__product-lists__product-list
    = link_to item_path(item), data:{"turbolinks" => false}, class: "line" do
      .pickup-container__product-box__product-lists__product-list__img
        = image_tag item.first_image.url.url, class: "img_k"
      .items-box_photo
      .body
        .body__name
          = item.name
        %ul.body__details
          %li.body__details__price
            = convertToJPY(item.price)
            円
          %li.body__details__star
            ★0
        .body__tax
          (税込)

- else
  .pickup-container__product-box__product-lists__product-list
    = link_to item_path(item), data:{"turbolinks" => false}, class: "line" do
      .pickup-container__product-box__product-lists__product-list__img
        = image_tag item.first_image.url.url, class: "img_k"
      .items-box_photo__sold
        .items-box_photo__sold__inner
          SOLD
      .body
        .body__name
          = item.name
        %ul.body__details
          %li.body__details__price
            = item.price
            円
          %li.body__details__star
            ★0
        .body__tax
          (税込)

app/views/items/index.html.haml
.wrapper
  .header
    .header__box
      .header__box__upper
        .header__box__upper__title-icon
          = link_to root_path, data:{"turbolinks" => false} do
            =image_tag asset_path("logo.png"), class: "header-image"
        .header__box__upper__search
          = form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form|
            = form.text_field :keyword, placeholder: "キーワードから探す", class: "header__box__upper__search--input"
            %button{type: "submit", class: 'header__box__upper__search--btn'} 
              = icon('fas', 'search', class: 'search-icon')
      .header__box__navi
        .header__box__navi__left
          .header__box__navi__left__category
            カテゴリ
            %ul.category1
              - @parents.each do |parent|
                %li.parent__list
                  = link_to parent.name
                  %ul.category2
                    - parent.children.each do |child|
                      %li.child__list
                        =link_to child.name
                        %ul.category3
                          - child.children.each do |grandchild|
                            %li.grandchild__list
                              = link_to grandchild.name
          .header__box__navi__left__brand
            =link_to "#" , class:"header__box__navi__left__brand" do
              ブランド

        .header__box__navi__right
          - if user_signed_in?
            = link_to "マイページ", "/users", class:"header__box__navi__right__mypage"             
          - else
            =link_to "ログイン","/users/sign_in", class:"header__box__navi__right__login" 
            =link_to "新規登録","/users/sign_up", class:"header__box__navi__right__new", data:{"turbolinks" => false}
      .header__box__menuIcon
        = icon('fas', 'bars')
        メニュー

  .main-visual
    .main-visual__content
      .main-visual__content__subtitle
        人生を変えるフリマアプリ
      .main-visual__content__text
        FURIMAは誰でもかんたんに出品・購入できるフリマアプリです
      .main-visual__content__btn 
        = link_to "#" do    
          = image_tag asset_path("apple_Badge.png"), size: "180x53", class: "main-visual__content__btn__abtn"
        = link_to "#" do
          = image_tag asset_path("google_Badge.png"), size: "180x53", class: "main-visual__content__btn__gbtn"
      .main-visual__content__pict

  .introduction
    .introduction__subtitle
      FURIMAが選ばれる３つの理由
    .introduction__lists
      .introduction__lists__tag
        .introduction__lists__tag__src
          .number
            1
          .image
            = image_tag asset_path("pict-reason-01.jpg"), size: "306x306", class: "introduction__lists__tag__pict"
        .introduction__lists__tag__text
          %p 
            %span= "3分"
            ですぐ出品
        .introduction__lists__tag__comment
          スマホで入力するだけで<br/>簡単に出品できる！
      .introduction__lists__tag
        .introduction__lists__tag__src
          .number
            2
          .image
            = image_tag asset_path("pict-reason-02.jpg"), size: "306x306", class: "introduction__lists__tag__pict"
        .introduction__lists__tag__pict
        .introduction__lists__tag__text
          %p 
            %span= "シンプル"
            で使いやすい
        .introduction__lists__tag__comment
          めんどくさい入力は必要なく、<br/>検索も購入もスムーズ！
      .introduction__lists__tag
        .introduction__lists__tag__src
          .number
            3 
          .image  
            = image_tag asset_path("pict-reason-03.jpg"), size: "306x306", class: "introduction__lists__tag__pict"
        .introduction__lists__tag__pict
        .introduction__lists__tag__text
          %p
            手数料
            %span= "業界最安"
        .introduction__lists__tag__comment
          最大３%でお得に出品＆購入！

  .main-visual2
    .main-visual2__content
      .main-visual2__content__subtitle
        会員数日本一位
      .main-visual2__content__text
        FURIMAは、フリマアプリで最も人気。
      .main-visual2__content__text2
        出品・購入回数も業界最多です！
      .main-visual2__content__text3
        ほしかったあの商品に出会えるかもしれません。
      .main-visual2__content__btn
        = link_to "#" do
          = image_tag asset_path("apple_Badge.png"), size: "180x53", class: "main-visual__content__btn__abtn"
        = link_to "#" do
          = image_tag asset_path("google_Badge.png"), size: "180x53", class: "main-visual__content__btn__gbtn"
      .main-visual2__content__pict

  .midle
    .midle__subtitle
      FURIMAの特徴
    .midle__lists
      .midle__lists__tag
        .midle__lists__tag__src
          .image
            = image_tag asset_path("icon-01.png"), size: "306x306", class: "pict"
        .midle__lists__tag__text
          簡単に売り買いできる
        .midle__lists__tag__comment
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .midle__lists__tag
        .midle__lists__tag__src
          .image  
            = image_tag asset_path("icon-03.png"), size: "306x306", class: "pict"
        .midle__lists__tag__pict
        .midle__lists__tag__text
          売上金は即日振り込みに対応
        .midle__lists__tag__comment
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      .midle__lists__tag
        .midle__lists__tag__src 
          .image  
            = image_tag asset_path("icon-04.png"), size: "306x306", class: "pict"
        .midle__lists__tag__pict
        .midle__lists__tag__text
          様々な支払いに対応
        .midle__lists__tag__comment
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  .pickup
    .pickup-container
      %h2.head ピックアップカテゴリー
      .pickup-container__box
        .pickup-container__box__head
          = link_to "items/new" do
            %h3.title 新規投稿商品
        .pickup-container__box__lists
          = render @items

  .appBanner
    .appBanner__inner
      %h2.appBanner__inner__title　だれでもかんたん、人生を変えるフリマアプリ
      
      %p.appBanner__inner__text 今すぐ無料ダウンロード！
      .appBanner__inner__icon
        = image_tag asset_path("apple_Badge.png") ,class:"icon-apple" 
        = image_tag asset_path("google_Badge.png") ,class:"icon-google"

  .footer
    %ul.footer__contents
      %li.footer__contents__content
        .footer__contents__content__name
          FURIMAについて
        = link_to "#", class:"kaisya" do
          会社概要
        = link_to "#", class:"privacy" do
          プライバシーポリシー
        = link_to "#", class:"kiyaku" do
          FURIMA利用規約
        = link_to "#", class:"tokuyaku" do
          ポイントに関する特約
      %li.footer__contents__content
        .footer__contents__content__name
          FURIMAを見る
        = link_to "#", class:"category" do
          カテゴリー一覧
        = link_to "#", class:"bland" do
          ブランド一覧
      %li.footer__contents__content
        .footer__contents__content__name
          ヘルプ&ガイド
        = link_to "#", class:"guide" do
          FURIMAガイド
        = link_to "#", class:"guideline" do
          FURIMAロゴ利用ガイドライン
        = link_to "#", class:"info" do
          お知らせ
    =image_tag asset_path("logo-white.png"), class: "footer__logo"
    .copyright
      © FURIMA

- if user_signed_in? 
  .exhibition-btn
    =link_to "/items/new", data:{"turbolinks" => false} do
      .exhibition-btn__text
        出品する
      .exhibition-btn__image
        %i.fas.fa-camera.fa-3x

app/views/items/new.html.haml
.wrapper
  .exhibit
    .exhibit__header
      =link_to root_path , class: "exhibit__header__logo" do
        =image_tag asset_path("logo.png"),class: "exhibit__header__logo__image"

    .exhibit__main
      .exhibit__main__itemProfile
        .exhibit__main__itemProfile__inputForm
        = form_with( model: @item, url: items_path, local: true) do |f|
          = render 'layouts/error_messages', model: f.object
          .exhibit__main__itemProfile__inputForm__sellImage
            .exhibit__main__itemProfile__inputForm__sellImage__upload
              .exhibit__main__itemProfile__inputForm__sellImage__upload__head
                .notation 出品画像
                .formRequire 必須
              .exhibit__main__itemProfile__inputForm__sellImage__upload__attention
                最大5枚までアップロードできます
              .exhibit__main__itemProfile__inputForm__sellImage__upload__box
                .prev-content
                .label-content
                  %label{for: "item_item_imgs_attributes_0_url", class: "label-box", id: "label-box--0"}
                    %pre.label-box__text-visible クリックしてファイルをアップロード
                .hidden-content
                  = f.fields_for :item_imgs do |i|
                    = i.file_field :url, class: "hidden-field"
                    %input{class:"hidden-field", type: "file", name: "item[item_imgs_attributes][1][url]", id: "item_item_imgs_attributes_1_url" }
                    %input{class:"hidden-field", type: "file", name: "item[item_imgs_attributes][2][url]", id: "item_item_imgs_attributes_2_url" }
                    %input{class:"hidden-field", type: "file", name: "item[item_imgs_attributes][3][url]", id: "item_item_imgs_attributes_3_url" }
                    %input{class:"hidden-field", type: "file", name: "item[item_imgs_attributes][4][url]", id: "item_item_imgs_attributes_4_url" }
          .exhibit__main__itemProfile__inputForm__sellGoods
            .exhibit__main__itemProfile__inputForm__sellGoods__name
              .notation
                商品名
              .formRequire
                必須
            = f.text_field :name, class: "exhibitInput", placeholder: "40文字まで"
            .exhibit__main__itemProfile__inputForm__sellGoods__description
              .notation
                商品の説明
              .formRequire
                必須
            = f.text_area :introduction, class: "exhibitTextarea", placeholder: "商品の説明（必須1,000文字以内）（色、重さ、素材、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。"
            .exhibit__main__itemProfile__inputForm__sellGoods__wordCount
              0/1000
          .exhibit__main__itemProfile__inputForm__sellDetails
            .exhibit__main__itemProfile__inputForm__sellDetails__title
              商品の詳細
            .exhibit__main__itemProfile__inputForm__sellDetails__formBox
              .exhibit__main__itemProfile__inputForm__sellDetails__formBox__category
                .exhibit__main__itemProfile__inputForm__sellDetails__formBox__category__select
                  .notation
                    カテゴリー
                  .formRequire
                    必須
                = f.select :category_id, Category.where(ancestry: nil).pluck(:name), { prompt: "選択してください" }, {class: 'exhibitInput', id: 'parent_category'}
              .exhibit__main__itemProfile__inputForm__sellDetails__formBox__brand
                .exhibit__main__itemProfile__inputForm__sellDetails__formBox__brand__write
                  .notation
                    ブランド
                  .formAny
                    任意
                = f.collection_select :brand_id, Brand.all, :id, :name, { prompt: "選択してください" }, class: "exhibitInput"
              .exhibit__main__itemProfile__inputForm__sellDetails__formBox__brand
                .exhibit__main__itemProfile__inputForm__sellDetails__formBox__brand__write
                  .notation
                    サイズ
                  .formRequire
                    必須
                = f.collection_select :size_id, Size.all, :id, :name, { prompt: "選択してください" }, class: "exhibitInput"
              .exhibit__main__itemProfile__inputForm__sellDetails__formBox__brand
                .exhibit__main__itemProfile__inputForm__sellDetails__formBox__brand__write
                  .notation
                    配送方法
                  .formRequire
                    必須
                = f.collection_select :postage_type_id, PostageType.all, :id, :postage_type, { prompt: "選択してください" }, class: "exhibitInput"
              .exhibit__main__itemProfile__inputForm__sellDetails__formBox__state
                .exhibit__main__itemProfile__inputForm__sellDetails__formBox__state__select
                  .notation
                    商品の状態
                  .formRequire
                    必須
                = f.collection_select :item_condition_id, ItemCondition.all, :id, :item_condition, { prompt: "選択してください" }, class: "exhibitInput"
              
          .exhibit__main__itemProfile__inputForm__delivery
            .exhibit__main__itemProfile__inputForm__delivery__leftBox
              .exhibit__main__itemProfile__inputForm__delivery__leftBox__title
                配送について
                =link_to "#", class: "questionMark" do
                  (?)
            .exhibit__main__itemProfile__inputForm__delivery__formBox  
              .exhibit__main__itemProfile__inputForm__delivery__formBox__burden
                .exhibit__main__itemProfile__inputForm__delivery__formBox__burden__select
                  .notation
                    配送料の負担
                  .formRequire
                    必須
                = f.collection_select :postage_payer_id, PostagePayer.all, :id, :postagepayer, { prompt: "選択してください" }, class: "exhibitInput"
              .exhibit__main__itemProfile__inputForm__delivery__formBox__area
                .exhibit__main__itemProfile__inputForm__delivery__formBox__area__select
                  .notation
                    発送元の地域
                  .formRequire
                    必須
                = f.collection_select :prefecture_id, Prefecture.all, :id, :name, { prompt: "選択してください" }, class: "exhibitInput" 
              .exhibit__main__itemProfile__inputForm__delivery__formBox__days
                .exhibit__main__itemProfile__inputForm__delivery__formBox__days__select
                  .notation
                    発送までの日数
                  .formRequire
                    必須
                = f.collection_select :preparation_day_id, PreparationDay.all, :id, :preparation_day_name, { prompt: "選択してください" }, class: "exhibitInput"

          .exhibit__main__itemProfile__inputForm__sellPrice
            .exhibit__main__itemProfile__inputForm__sellPrice__leftBox
              .exhibit__main__itemProfile__inputForm__sellPrice__leftBox__title
                価格(￥300〜9,999,999)
                =link_to "#", class: "questionMark" do
                  (?)
            .exhibit__main__itemProfile__inputForm__sellPrice__calculation
              .exhibit__main__itemProfile__inputForm__sellPrice__calculation__priceForm
                .exhibit__main__itemProfile__inputForm__sellPrice__calculation__priceForm__amountOfSales
                  .notation
                    販売価格
                  .formRequire
                    必須
                = f.text_field :price,class: "exhibitInput", placeholder: "例）300〜9,999,999"

          .exhibit__main__itemProfile__inputForm__warning
            = f.submit :出品する ,class: "exhibitSubmit1"
            = link_to "root_path", class: "exhibitSubmit2" do
              もどる
            .exhibit__main__itemProfile__inputForm__warning__links
              %span.exhibit__main__itemProfile__inputForm__warning__links__link
                禁止されている
              =link_to "#" do
                行為
              %span.exhibit__main__itemProfile__inputForm__warning__links__link
                および
              =link_to "#" do
                出品物
              %span.exhibit__main__itemProfile__inputForm__warning__links__link
                を必ずご確認ください。
              =link_to "#" do
                偽ブランド品
              %span.exhibit__main__itemProfile__inputForm__warning__links__link
                や
              =link_to "#" do
                盗品物
              %span.exhibit__main__itemProfile__inputForm__warning__links__link
                などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして
              =link_to "#" do
                加盟店規約
              %span.exhibit__main__itemProfile__inputForm__warning__links__link
                に同意したことになります。

    .exhibit__footer
      .exhibit__footer__lists
        =link_to "#", class: "exhibit__footer__lists__list" do
          プライバシーポリシー
        =link_to "#", class: "exhibit__footer__lists__list" do
          Furima利用規約
        =link_to "#", class: "exhibit__footer__lists__list" do
          特定商取引に関する表記   
      =link_to "#" , class: ".exhibit__footer__logo" do
        =image_tag asset_path("logo.png"),class: "exhibit__footer__logo__image"
      .exhibit__footer__ending
        © Furima, Inc.

app/views/items/search.html.haml
.wrapper
  .header
    .header__box
      .header__box__upper
        .header__box__upper__title-icon
          = link_to root_path, data:{"turbolinks" => false} do
            =image_tag asset_path("logo.png"), class: "header-image"
        .header__box__upper__search
          = form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form|
            = form.text_field :keyword, placeholder: "キーワードから探す", class: "header__box__upper__search--input"
            %button{type: "submit", class: 'header__box__upper__search--btn'} 
              = icon('fas', 'search', class: 'search-icon')
      .header__box__navi
        .header__box__navi__left
          .header__box__navi__left__category
            カテゴリ
            %ul.category1
              - @parents.each do |parent|
                %li.parent__list
                  = link_to parent.name
                  %ul.category2
                    - parent.children.each do |child|
                      %li.child__list
                        =link_to child.name
                        %ul.category3
                          - child.children.each do |grandchild|
                            %li.grandchild__list
                              = link_to grandchild.name
          .header__box__navi__left__brand
            =link_to "#" , class:"header__box__navi__left__brand" do
              ブランド

        .header__box__navi__right
          - if user_signed_in?
            = link_to "マイページ", "/users", class:"header__box__navi__right__mypage"             
          - else
            =link_to "ログイン","/users/sign_in", class:"header__box__navi__right__login" 
            =link_to "新規登録","/users/sign_up", class:"header__box__navi__right__new", data:{"turbolinks" => false}
      .header__box__menuIcon
        = icon('fas', 'bars')
        メニュー
  .main
    .search
      .search-container
        .search-container__head
          キーワード検索
        .search-container__product-box
          .search-container__product-box__product-head
            = link_to "#", class: "line" do
              = "検索結果: #{@items.length}件"
        .search-container__product-lists
          = render @items
  .appBanner
    .appBanner__inner
      %h2.appBanner__inner__title　だれでもかんたん、人生を変えるフリマアプリ
      
      %p.appBanner__inner__text 今すぐ無料ダウンロード！
      .appBanner__inner__icon
        = image_tag asset_path("apple_Badge.png") ,class:"icon-apple" 
        = image_tag asset_path("google_Badge.png") ,class:"icon-google"

  .footer
    %ul.footer__contents
      %li.footer__contents__content
        .footer__contents__content__name
          FURIMAについて
        = link_to "#", class:"kaisya" do
          会社概要
        = link_to "#", class:"privacy" do
          プライバシーポリシー
        = link_to "#", class:"kiyaku" do
          FURIMA利用規約
        = link_to "#", class:"tokuyaku" do
          ポイントに関する特約
      %li.footer__contents__content
        .footer__contents__content__name
          FURIMAを見る
        = link_to "#", class:"category" do
          カテゴリー一覧
        = link_to "#", class:"bland" do
          ブランド一覧
      %li.footer__contents__content
        .footer__contents__content__name
          ヘルプ&ガイド
        = link_to "#", class:"guide" do
          FURIMAガイド
        = link_to "#", class:"guideline" do
          FURIMAロゴ利用ガイドライン
        = link_to "#", class:"info" do
          お知らせ
    =image_tag asset_path("logo-white.png"), class: "footer__logo"
    .copyright
      © FURIMA

- if user_signed_in? 
  .exhibition-btn
    =link_to "/items/new", data:{"turbolinks" => false} do
      .exhibition-btn__text
        出品する
      .exhibition-btn__image
        %i.fas.fa-camera.fa-3x