config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'sending_destinations', to: 'users/registrations#new_sending_destination'
    post 'sending_destinations', to: 'users/registrations#create_sending_destination'
  end
  root "items#index"

  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: :show do
      collection do
        post 'pay'
      end
    end
    collection do
      get 'search'
    end
  end
  resources :users do
    collection do
      get 'credit_register'
      get 'logout'
    end
  end
  resources :credit_cards, only: [:new, :create, :show, :destroy] 
end

app/views/layouts/_error_messages.html.haml
-if @item.errors.any? 
  .alert
    %ul
      -@item.errors.full_messages.each do |message|
        %li= message

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_user_side_navi.html.haml
.user-mypage-wrapper__navi
  .user-mypage-wrapper__navi__menu
    %ul
      %li
        = link_to "#" do
          マイページ
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          お知らせ
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          やることリスト
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          いいね！一覧
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          出品する
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          出品した商品-出品中
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          出品した商品-取引中
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          出品した商品-売却済み
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          購入した商品-取引中
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          購入した商品-過去の取引
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          ニュース一覧
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          評価一覧
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          ガイド
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          お問い合わせ
          %i.fas.fa-chevron-right.menu-icon
  .user-mypage-wrapper__navi__merpay
    %h3 メルペイ
    %ul
      %li
        = link_to "#" do
          売上・振込申請
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          ポイント
          %i.fas.fa-chevron-right.menu-icon
  .user-mypage-wrapper__navi__config
    %h3 設定
    %ul 
      %li
        = link_to "#" do
          プロフィール
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to credit_register_users_path do
          支払い方法
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          メール/パスワード
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#"  do
          本人情報
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "#" do
          電話番号の確認
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to logout_users_path do
          ログアウト          
          %i.fas.fa-chevron-right.menu-icon

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FreemarketSample73j
    %script{src: "https://js.pay.jp", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = include_gon(init: true)
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield